# -*- coding: utf-8 -*-
"""Data Analytics From Medium

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MgtwdhEyQJiOQH7Khc1SouIiCUWFd1Q5
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

medium_data = pd.read_csv('medium_data_clear.csv',parse_dates= ['date'],dayfirst=True)

no_id = medium_data
df = no_id[['date','publication','title','subtitle','reading_time','responses','claps','url']].copy()
df.head(2)

"""Popular Articles"""

#Readingtime view
df3=df[['date','publication','title','reading_time','responses','claps']]

readingtime_view =df3.sort_values(by =['reading_time'], ascending=False)
readingtime_view.head()

#claps view
claps_view =df3.sort_values(by =['claps'], ascending=False)
claps_view.head(5)

#date view
date_upload=df3.sort_values(by =['date'], ascending=True)
date_upload

"""Comparison of the intensity of uploading articles for each publisher"""

date_upload['publication'].unique()

#Article Upload Corp 1
corp_1 = date_upload[date_upload['publication']=='The Writing Cooperative'].copy()
corp_1['article_count_corp_1'] = 1
corp_1 = corp_1[['date','article_count_corp_1']]

#Data Upload record
record_upload_corp_1 = corp_1.groupby(['date']).count()
c1 = record_upload_corp_1

#output test
# corp_1.head(2)
# c1

#Article Upload Corp 2
corp_2 = date_upload[date_upload['publication']=='The Startup'].copy()
corp_2['article_count_corp_2'] = 1
corp_2 = corp_2[['date','article_count_corp_2']]
record_upload_corp_2 = corp_2.groupby(['date']).count()
c2 = record_upload_corp_2

#Article Upload Corp 3
corp_3 = date_upload[date_upload['publication']=='Towards Data Science'].copy()
corp_3['article_count_corp_3'] = 1
corp_3 = corp_3[['date','article_count_corp_3']]
record_upload_corp_3 = corp_3.groupby(['date']).count()
c3 = record_upload_corp_3

#Article Upload Corp 4
corp_4 = date_upload[date_upload['publication']=='UX Collective'].copy()
corp_4['article_count_corp_4'] = 1
corp_4 = corp_4[['date','article_count_corp_4']]
record_upload_corp_4 = corp_4.groupby(['date']).count()
c4 = record_upload_corp_4

#Join c1,c2,c3,c4 
join_c1c2 = c1.set_index(c1.index).join(c2.set_index(c2.index),how='outer')
join_c3c4 = c3.set_index(c3.index).join(c4.set_index(c4.index),how='outer')

freg_upload = join_c1c2.set_index(join_c1c2.index).join(join_c3c4.set_index(join_c3c4.index), how = 'outer')

#output test
# join_c1c2.head(2)
# join_c3c4.head(2)
freg_upload.head()

#data cleaning
freg_upload.fillna(0,inplace=True)
freg_upload['article_count_corp_3'] = freg_upload['article_count_corp_3'].astype('int')
freg_upload['article_count_corp_4'] = freg_upload['article_count_corp_4'].astype('int')
freg_upload

import matplotlib.dates as mdates

time = freg_upload.index
pub_1 = freg_upload['article_count_corp_1']
pub_2 = freg_upload['article_count_corp_2']
pub_3 = freg_upload['article_count_corp_3']
pub_4 = freg_upload['article_count_corp_4']

locator = mdates.DayLocator(bymonthday=[1, 8, 15, 22])
formatter = mdates.DateFormatter('%d %b')

fig, ax = plt.subplots(figsize=(10, 6), tight_layout=True)
ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(formatter)
ax.tick_params(axis='x', rotation=0)
#set data
ax.plot(time, pub_1)
ax.plot(time, pub_2)
ax.plot(time, pub_3)
ax.plot(time, pub_4)

ax.grid(True)
ax.set_xlabel('Time')
ax.set_ylabel('Upload Frequency Article')
ax.legend(['The Writing Cooperative','The Startup','Towards Data Science','UX Collective'])
ax.set_title('''
Frekuensi Mengunggah Artikel 
Bulan Januari - April Tahun 2023
''')
plt.show()

"""Comparison between reading time, responses, and claps based on the average and the number of articles that have been uploaded"""

import matplotlib.pyplot as plt
import seaborn as sns

only_data = df[['publication','reading_time','responses','claps']]

#output
only_data

#visualisation
plt.figure(figsize=(14,5))
sns.boxplot(data=only_data, y='publication', x='reading_time')
plt.xlabel('Frekuensi Waktu Baca')
plt.ylabel('Publiser')
plt.title('''
Perbandingan Lama Waktu Baca Artikel Medium Tahun 2023 
''')

import matplotlib.pyplot as plt
import seaborn as sns

only_data = df[['publication','reading_time','responses','claps']]

#output
only_data

#visualisation
plt.figure(figsize=(14,5))
sns.boxplot(data=only_data, y='publication', x='responses')
plt.xlabel('Frekuensi Komentar')
plt.ylabel('Publiser')
plt.title('''
Perbandingan Jumlah Komentar Artikel Medium Tahun 2023 
''')

import matplotlib.pyplot as plt
import seaborn as sns

only_data = df[['publication','reading_time','responses','claps']]

#output
only_data

#visualisation
plt.figure(figsize=(14,5))
sns.boxplot(data=only_data, y='publication', x='claps')
plt.xlabel('Frekuensi Tepuk Tangan')
plt.ylabel('Publiser')
plt.title('''
Perbandingan Jumlah Tepuk Tangan Artikel Medium Tahun 2023 
''')

import matplotlib.pyplot as plt

article_count = df[['publication','title','subtitle']]

publiser = article_count.groupby(['publication']).count()

#output
print(publiser)
plt.barh(publiser.index,publiser['title'])
plt.tick_params(axis='x', rotation=90)
plt.xlabel('Frekuensi')
plt.ylabel('Publiser')
plt.title('''
Frekuensi Upload Artikel Tahun 2023 
''')